### ISSUE TITLE
Unknown status returned by CPLEX

### ISSUE THREAD

**Issue by Kuifje02** [coin-or/pulp#295]
Details for the issue
--------------------

#### What did you do?

I tried solving a MIP with PuLP and CPLEX 12.9.0.0. : `prob.solve(pulp.solvers.CPLEX_CMD())`

#### What happened ?

`pulp.solvers.PulpSolverError: Unknown status returned by CPLEX: integer optimal solution`

If I solve the problem directly with CPLEX (without PuLp) : 

![image](https://user-images.githubusercontent.com/19840033/83359008-a8ffe600-a377-11ea-9ff3-185945c4f993.png)

So apparently PuLp does not recognize the status returned by CPLEX. Maybe this status is new?

#### Note

- the MIP has a dummy objective function (a constant: 0). I think the status returned by CPLEX is linked to this.

- I have attached the .lp file in case it helps: [subprob_cplexerror.zip](https://github.com/coin-or/pulp/files/4708100/subprob_cplexerror.zip)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version: 10 pro )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.8.2

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ ] github
- [ ] Other: ___

**Comment by pchtsp** [comment]
Hello and thanks for the ticket. Can you also provide the python code so as to run it with pulp? Solving the lp via cplex does not provide the return code in the logs.

**Comment by Kuifje02** [comment]
The lp is actually part of a big program. It would not be practical if I provided the code as is. But I do understand we need it to reproduce the error and fix it. I will try and figure something out!

**Comment by pchtsp** [comment]
in case it can be help to debug the problem, there is some experimental functionality in pulp to export a problem in the https://github.com/coin-or/pulp/tree/export_pb branch. check these lines in tests that show how to do it: 

https://github.com/coin-or/pulp/blob/c91f55ae2be5b3813f159485587be87303bb1d24/pulp/tests/test_pulp.py#L666

You can export the model into json, then import it into a fresh python session and see if you can reproduce it. If so, just put here the json file and I'll give it a try.

**Comment by Kuifje02** [comment]
Sorry I've been struggling with the export_pb branch and for the moment cannot export the model into json. 
In the mean time, the status appears [here](https://www.gams.com/latest/docs/S_CPLEX.html) (GAMS docs):

![image](https://user-images.githubusercontent.com/19840033/83395790-359fb800-a3fb-11ea-91dc-7d06f2d6878a.png)

So we can see the code is CPLEX STATUS 101, which appears in the cplex docs [here](http://www-eio.upc.es/lceio/manuals/cplex-11/html/overviewcplex/statuscodes.html):

![image](https://user-images.githubusercontent.com/19840033/83395906-61bb3900-a3fb-11ea-9705-2d1ab49027b4.png)

I will give the json export another try when I can.

**Comment by stumitchell** [comment]
I think we would be happy to change the code here for you https://github.com/coin-or/pulp/blob/ca9b3941a82c4433d7e1a17bd785df07d09d8948/pulp/apis/cplex_api.py#L102

If you could please find the place in the cplex documentation where these strings are defined 
OR
attach us your .sol file from running it yourself.

Preferably both

Thanks

**Comment by stumitchell** [comment]
It seems we are relying on a string here when we should probably look in the solution file for a int status code.

**Comment by Kuifje02** [comment]
> attach us your .sol file from running it yourself.

Here is the .sol file is attached [pulp.zip](https://github.com/coin-or/pulp/files/4715030/pulp.zip). We can see the following :

  ```
 solutionStatusValue="101"
 solutionStatusString="integer optimal solution"
```
whereas normally it is 

  ```
 solutionStatusValue="1"
 solutionStatusString="optimal"
```

> If you could please find the place in the cplex documentation where these strings are defined

The cplex documentation with the above strings is found [here](http://www-eio.upc.es/lceio/manuals/cplex-11/html/overviewcplex/statuscodes.html).


It is still unclear to me though why this happens. It only happens for specific data sets, where the exact same lp is defined. Only the data changes.

**Comment by pchtsp** [comment]
Hello, I was just checking the pulp code. Indeed it's kind of a mystery why it has been working well all of this time. 

I've been using pulp with cplex for some years now and I had never had issues with the status of the solution returned, even in cases where the solution is integer feasible (not proven optimal), I'm guessing cplex returns 'optimal' in the solutionStatusString (because there were no errors from pulp).

I propose we pivot to using the cplex codes instead of the strings and just add the "101" for now as optimal.

```
statusString = solutionheader.get("solutionStatusString")
statusValue = solutionheader.get("solutionStatusValue")
# TODO: check status for Integer Feasible
cplexStatus = {
    "1": constants.LpStatusOptimal,
    "101": constants.LpStatusOptimal,
    }
if statusValue not in cplexStatus:
    raise PulpSolverError("Unknown status returned by CPLEX: \ncode: '{}', string: '{}'".
                          format(statusValue, statusString))
```

I'm not sure if we should make a mapping for all the cplex codes in the site (by the way, thanks @Kuifje02 for the link, I never find the codes when I want them). 

Maybe adding the most important ones, as we have with the CPLEX_PY api makes sense. Even if they are not used...

**Comment by Kuifje02** [comment]
> I've been using pulp with cplex for some years now and I had never had issues with the status of the solution returned, even in cases where the solution is integer feasible (not proven optimal), I'm guessing cplex returns 'optimal' in the solutionStatusString (because there were no errors from pulp).

Same here, I have been using PuLp and CPLEX for years and have never encountered this problem. Maybe it is because CPLEX has updated its statuses ? It remains a mystery to me what the difference is between optimal and integer optimal (because some integer optimal solutions are returned with the "optimal" status).
